/* ============================================================================
 * RLBotMainA.java — RL-optimized main bot (3 per team).
 * All strategy constants read from RLConfigA (generated by rl_train.py).
 * ============================================================================*/
package algorithms.rla;

import characteristics.IRadarResult;
import characteristics.Parameters;

public class RLBotMainA extends RLBotBaseA {

    private double holdX, holdY;
    private double kiteMin, kiteMax;
    private int noFireTicks = 0;

    @Override
    public void activate() {
        teamA = (getHeading() == Parameters.EAST);

        boolean hasN = false, hasS = false;
        for (IRadarResult o : detectRadar()) {
            if (aDist(o.getObjectDirection(), Parameters.NORTH) < ANGLE_PREC) hasN = true;
            if (aDist(o.getObjectDirection(), Parameters.SOUTH) < ANGLE_PREC) hasS = true;
        }
        if (hasN && hasS)       id = M2;
        else if (!hasN && hasS) id = M1;
        else                    id = M3;

        if      (M1.equals(id)) { myX = teamA ? Parameters.teamAMainBot1InitX : Parameters.teamBMainBot1InitX;
                                  myY = teamA ? Parameters.teamAMainBot1InitY : Parameters.teamBMainBot1InitY; }
        else if (M2.equals(id)) { myX = teamA ? Parameters.teamAMainBot2InitX : Parameters.teamBMainBot2InitX;
                                  myY = teamA ? Parameters.teamAMainBot2InitY : Parameters.teamBMainBot2InitY; }
        else                    { myX = teamA ? Parameters.teamAMainBot3InitX : Parameters.teamBMainBot3InitX;
                                  myY = teamA ? Parameters.teamAMainBot3InitY : Parameters.teamBMainBot3InitY; }

        holdX = teamA ? RLConfigA.HOLD_X_OFFSET : (MAP_W - RLConfigA.HOLD_X_OFFSET);
        double[] holdYs = {740.0, 1000.0, 1260.0};
        holdY = holdYs[M1.equals(id) ? 0 : M2.equals(id) ? 1 : 2];

        state = S.ADVANCING;
        resumeState = S.ADVANCING;
        kiteMin = RLConfigA.KITE_MIN_NORMAL;
        kiteMax = RLConfigA.KITE_MAX_NORMAL;

        UAlly self = allies.get(id);
        self.update(myX, myY, getHeading());
        self.alive = true;
    }

    @Override
    public void step() {
        if (fireCooldown > 0) fireCooldown--;
        scanRadar();
        readMessages();
        ageEnemies();

        if (getHealth() <= 0) {
            state = S.DEAD;
            allies.get(id).alive = false;
            broadcast("DEAD " + id);
            return;
        }

        broadcast("POS " + id + " " + myX + " " + myY + " " + getHeading());
        updateKiteRange();

        // First fire attempt (before movement)
        UEnemy t = chooseTarget();
        boolean fired = tryFire(t);
        if (t != null) {
            if (fired) {
                noFireTicks = 0;
            } else {
                noFireTicks++;
            }
        } else {
            noFireTicks = 0;
        }

        // Elect and broadcast focus target every step so all bots converge fire
        electFocusTarget();

        // State transitions
        if (!isAvoiding() && state != S.DEAD) {
            if (getHealth() < RLConfigA.HP_RETREAT_MAIN && enemies.isEmpty()) {
                state = S.RETREATING;
            } else if (!enemies.isEmpty()) {
                state = (noFireTicks > RLConfigA.NOFIRE_REPOSITION_TICKS) ? S.FLANKING : S.FIRING;
            } else {
                state = S.ADVANCING;
            }
        }

        switch (state) {
            case ADVANCING: {
                double pushX = teamA ? Math.min(MAP_W - 250.0, holdX + 350.0)
                                     : Math.max(250.0, holdX - 350.0);
                double tx = (Math.hypot(myX - holdX, myY - holdY) < 80.0) ? pushX : holdX;
                goTo(tx, holdY);
                break;
            }
            case FIRING: potentialFieldCombatMove(); break;
            case FLANKING: clearShotReposition(); break;
            case RETREATING: retreat(); break;
            case HOLDING: break;
            case TURN_LEFT: case TURN_RIGHT: case BACK: doAvoidStep(); break;
            default: break;
        }

        // Second fire attempt (after movement)
        t = chooseTarget();
        fired = tryFire(t);
        if (t != null && fired) {
            noFireTicks = 0;
        }
    }

    private void updateKiteRange() {
        int aliveAllies = countAliveAllies();
        double myHP = getHealth();
        if (aliveAllies >= 3 && myHP > 200) {
            kiteMin = RLConfigA.KITE_MIN_AGGRO;
            kiteMax = RLConfigA.KITE_MAX_AGGRO;
        } else if (aliveAllies <= 1 || myHP < 100) {
            kiteMin = RLConfigA.KITE_MIN_DEFEN;
            kiteMax = RLConfigA.KITE_MAX_DEFEN;
        } else {
            kiteMin = RLConfigA.KITE_MIN_NORMAL;
            kiteMax = RLConfigA.KITE_MAX_NORMAL;
        }
    }

    private void potentialFieldCombatMove() {
        double angle = potentialFieldAngle(kiteMin, kiteMax);
        if (!isFacing(angle)) stepTurnTo(angle);
        else doMove(true);
    }

    private void clearShotReposition() {
        double offsetY;
        if (M1.equals(id))      offsetY = -150.0;
        else if (M3.equals(id)) offsetY = 150.0;
        else                    offsetY = (myY < 1000 ? 120.0 : -120.0);

        double tx = myX + (teamA ? 50 : -50);
        double ty = myY + offsetY;
        tx = Math.max(200, Math.min(MAP_W - 200, tx));
        ty = Math.max(200, Math.min(MAP_H - 200, ty));
        goTo(tx, ty);
    }

    private void retreat() {
        double safeX = teamA ? 300.0 : MAP_W - 300.0;
        goTo(safeX, holdY);
    }
}
