/* ============================================================================
 * RLBotSecondaryA.java — RL-optimized secondary/scout bot (2 per team).
 * All strategy constants read from RLConfigA (generated by rl_train.py).
 * ============================================================================*/
package algorithms.rla;

import characteristics.IRadarResult;
import characteristics.Parameters;

public class RLBotSecondaryA extends RLBotBaseA {

    private double flankY;
    private double advanceX;
    private boolean flankReached = false;

    @Override
    public void activate() {
        teamA = (getHeading() == Parameters.EAST);

        id = NBOT;
        for (IRadarResult o : detectRadar()) {
            if (aDist(o.getObjectDirection(), Parameters.NORTH) < ANGLE_PREC)
                id = SBOT;
        }

        if (NBOT.equals(id)) {
            myX = teamA ? Parameters.teamASecondaryBot1InitX : Parameters.teamBSecondaryBot1InitX;
            myY = teamA ? Parameters.teamASecondaryBot1InitY : Parameters.teamBSecondaryBot1InitY;
            flankY = RLConfigA.FLANK_Y_OFFSET;
        } else {
            myX = teamA ? Parameters.teamASecondaryBot2InitX : Parameters.teamBSecondaryBot2InitX;
            myY = teamA ? Parameters.teamASecondaryBot2InitY : Parameters.teamBSecondaryBot2InitY;
            flankY = MAP_H - RLConfigA.FLANK_Y_OFFSET;
        }

        advanceX = teamA ? RLConfigA.ADVANCE_X_A : (MAP_W - RLConfigA.ADVANCE_X_A);

        state = S.INIT;
        resumeState = S.INIT;

        UAlly self = allies.get(id);
        self.update(myX, myY, getHeading());
        self.alive = true;
    }

    @Override
    public void step() {
        if (fireCooldown > 0) fireCooldown--;
        scanRadar();
        readMessages();
        ageEnemies();

        if (getHealth() <= 0) {
            state = S.DEAD;
            allies.get(id).alive = false;
            broadcast("DEAD " + id);
            return;
        }

        broadcast("POS " + id + " " + myX + " " + myY + " " + getHeading());

        // Secondaries also participate in focus fire — shoot at any enemy in range
        UEnemy t = chooseTarget();
        tryFire(t);

        double maxHP = Parameters.teamASecondaryBotHealth;
        if (getHealth() < maxHP * RLConfigA.HP_RETREAT_PCT_SEC && state != S.RETREATING && state != S.DEAD) {
            if (!isAvoiding()) state = S.RETREATING;
        }

        switch (state) {
            case INIT: executeFlankRush(); break;
            case FLANKING: executeAdvance(); break;
            case ADVANCING: executePatrol(); break;
            case RETREATING: executeRetreat(); break;
            case TURN_LEFT: case TURN_RIGHT: case BACK: doAvoidStep(); break;
            default: break;
        }
    }

    private void executeFlankRush() {
        if (Math.abs(flankY - myY) < 30.0) {
            flankReached = true;
            state = S.FLANKING;
            return;
        }
        double targetAngle = NBOT.equals(id) ? 3.0 * Math.PI / 2.0 : Math.PI / 2.0;
        if (!isFacing(targetAngle)) stepTurnTo(targetAngle);
        else doMove(true);
    }

    private void executeAdvance() {
        boolean mainAlive = false;
        for (String mid : new String[]{M1, M2, M3}) {
            UAlly a = allies.get(mid);
            if (a != null && a.alive) { mainAlive = true; break; }
        }
        if (!mainAlive) { state = S.RETREATING; return; }

        if (Math.abs(advanceX - myX) < 50.0) { state = S.ADVANCING; return; }

        double targetAngle = teamA ? 0.0 : Math.PI;
        if (!isFacing(targetAngle)) stepTurnTo(targetAngle);
        else doMove(true);
    }

    private void executePatrol() {
        if (!enemies.isEmpty()) {
            double minDist = Double.MAX_VALUE;
            for (UEnemy e : enemies) {
                double d = Math.hypot(e.x - myX, e.y - myY);
                if (d < minDist) minDist = d;
            }
            if (minDist < RLConfigA.PATROL_EVASION_RANGE) {
                double angle = potentialFieldAngle(250.0, 500.0);
                if (!isFacing(angle)) stepTurnTo(angle);
                else doMove(true);
                return;
            }
        }

        double targetAngle = teamA ? 0.0 : Math.PI;
        if ((teamA && myX > 2400) || (!teamA && myX < 600))
            targetAngle = teamA ? Math.PI : 0.0;
        if (myY < 200) targetAngle = Math.PI / 2.0;
        if (myY > MAP_H - 200) targetAngle = 3.0 * Math.PI / 2.0;

        if (!isFacing(targetAngle)) stepTurnTo(targetAngle);
        else doMove(true);
    }

    private void executeRetreat() {
        double safeX = teamA ? 350.0 : MAP_W - 350.0;
        double safeY = NBOT.equals(id) ? 300.0 : MAP_H - 300.0;
        if (Math.hypot(myX - safeX, myY - safeY) < 100) return;
        goTo(safeX, safeY);
    }
}
